{
 "title": "SVCi - IBM Storage - Overview",
 "description": "https://git.data.coop/nellemann/svci/ - Metrics collected from IBM Spectrum Virtualize.",
 "time": { "from": "now-6h", "to": "now-30s" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"name\" WHERE time > now() - 24h"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "SHOW TAG VALUES FROM \"node_stats\" WITH KEY = \"name\" WHERE \"system\" =~ /$system/  AND time > now() - 24h"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Storage\n    \nFor more information visit: [github.com/mnellemann/svci](https://github.com/mnellemann/svci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Details",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "8h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "location" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Location" ], "type": "alias" }
      ],
      [
       { "params": [ "product_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Product" ], "type": "alias" }
      ],
      [
       { "params": [ "code_level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Code Level" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Frontend Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "fc_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "FC" ], "type": "alias" }
      ],
      [
       { "params": [ "iscsi_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "iSCSI" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Frontend Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "fc_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "FC" ], "type": "alias" }
      ],
      [
       { "params": [ "iscsi_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iSCSI" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Drives Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "drive_r_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "drive_w_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Drives Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "drive_r_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "drive_w_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Drives Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "drive_r_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "drive_w_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "cpu_pc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "System" ], "type": "alias" }
      ],
      [
       { "params": [ "compression_cpu_pc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Compression" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "total_cache_pc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "write_cache_pc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Enclosure Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enclosure_stats",
     "select": [
      [
       { "params": [ "power_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Watt" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Enclosure Temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_system - $tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enclosure_stats",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Temp" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "VDisk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "vdisk_r_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "vdisk_w_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "VDisk Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "vdisk_r_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "vdisk_w_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "VDisk Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "vdisk_r_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "vdisk_w_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "MDisk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "mdisk_r_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "mdisk_w_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "MDisk Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "mdisk_r_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "mdisk_w_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "MDisk Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "mdisk_r_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "mdisk_w_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "SAS Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "sas_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "SAS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Cloud Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "cloud_down_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "cloud_up_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "IPLink Troughtput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "iplink_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "MB" ], "type": "alias" }
      ],
      [
       { "params": [ "iplink_comp_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "MB" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "SAS Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "sas_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "SAS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Cloud Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "cloud_down_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "cloud_up_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Up" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "IPLink Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name : $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_stats",
     "select": [
      [
       { "params": [ "iplink_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Volumes / Pool",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "repeat": "system",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_system - $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "m_disk_groups",
     "select": [
      [
       { "params": [ "vdisk_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "V Disks" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  }
 ]
}