# SVCi Configuration

###
### Define one InfluxDB to save metrics into
### There must be only one and it should be named [influx]
###

# InfluxDB v1.x example
#[influx]
#url = "http://localhost:8086"
#username = "root"
#password = ""
#database = "svci"

# InfluxDB v2.x example
[influx]
url = "http://localhost:8086"
org = "myOrg"
token = "rAnd0mT0k3nG3neRaT3dByInF1uxDb=="
bucket = "svci"


###
### Define one or more SVC's to query for metrics
### Each entry must be named [svc.<something-unique>]
###

# SVC on our primary site
[svc.site1]
url = "https://10.10.10.12:7443"
username = "superuser"
password = "password"
refresh = 30
trust = true   # Ignore SSL cert. errors

