# SVCi Configuration
# Copy this file into /etc/svci.toml and customize it to your environment.

###
### Define one InfluxDB to save metrics into
###

[influx]
url = "http://localhost:8086"
username = "root"
password = ""
database = "svci"


###
### Define one or more SVC's to query for metrics
### Each entry must be named [svc.<something-unique>]
###

[svc.site1]
url = "https://10.10.10.5:7443"
username = "superuser"
password = "password"
refresh = 30   # How often to query SVC for data - in seconds
trust = true   # Ignore SSL cert. errors (due to default self-signed cert.)

