[
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "0",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "0",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "7",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   },
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "1",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "1",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "6",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   },
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "2",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "2",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "2",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   },
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "3",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "3",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "8",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   },
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "4",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "4",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "9",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   },
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "5",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "5",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "3",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   },
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "6",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "6",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "5",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   },
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "7",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "7",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "4",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   },
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "8",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "8",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "1",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   },
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "9",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "9",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "10",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   },
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "10",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "10",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "11",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   },
   {
      "auto_manage" : "inactive",
      "capacity" : "20.0TB",
      "drive_class_id" : "0",
      "enclosure_id" : "1",
      "error_sequence_number" : "",
      "id" : "11",
      "mdisk_id" : "0",
      "mdisk_name" : "MDisk1",
      "member_id" : "11",
      "node_id" : "",
      "node_name" : "",
      "slot_id" : "12",
      "status" : "online",
      "tech_type" : "tier0_flash",
      "use" : "member"
   }
]
