[
   {
      "WWPN" : "500507680B11FFC8",
      "adapter_location" : "1",
      "adapter_port_id" : "1",
      "attachment" : "switch",
      "cluster_use" : "local_partner",
      "fc_io_port_id" : "1",
      "id" : "0",
      "node_id" : "1",
      "node_name" : "node1",
      "nportid" : "012200",
      "port_id" : "1",
      "port_speed" : "32Gb",
      "status" : "active",
      "type" : "fc"
   },
   {
      "WWPN" : "500507680B12FFC8",
      "adapter_location" : "1",
      "adapter_port_id" : "2",
      "attachment" : "switch",
      "cluster_use" : "local_partner",
      "fc_io_port_id" : "2",
      "id" : "1",
      "node_id" : "1",
      "node_name" : "node1",
      "nportid" : "011D00",
      "port_id" : "2",
      "port_speed" : "32Gb",
      "status" : "active",
      "type" : "fc"
   },
   {
      "WWPN" : "500507680B11FFC9",
      "adapter_location" : "1",
      "adapter_port_id" : "1",
      "attachment" : "switch",
      "cluster_use" : "local_partner",
      "fc_io_port_id" : "1",
      "id" : "24",
      "node_id" : "2",
      "node_name" : "node2",
      "nportid" : "012000",
      "port_id" : "1",
      "port_speed" : "32Gb",
      "status" : "active",
      "type" : "fc"
   },
   {
      "WWPN" : "500507680B12FFC9",
      "adapter_location" : "1",
      "adapter_port_id" : "2",
      "attachment" : "switch",
      "cluster_use" : "local_partner",
      "fc_io_port_id" : "2",
      "id" : "25",
      "node_id" : "2",
      "node_name" : "node2",
      "nportid" : "011F00",
      "port_id" : "2",
      "port_speed" : "32Gb",
      "status" : "active",
      "type" : "fc"
   }
]
