{
 "title": "SVCi - IBM Storage - IO Stats",
 "description": "https://git.data.coop/nellemann/svci/ - Metrics collected from IBM Spectrum Virtualize.",
 "time": { "from": "now-6h", "to": "now-30s" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"name\" WHERE time > now() - 24h"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "SHOW TAG VALUES FROM \"node_stats\" WITH KEY = \"name\" WHERE \"system\" =~ /$system/  AND time > now() - 24h"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Storage\n    \nFor more information visit: [github.com/mnellemann/svci](https://github.com/mnellemann/svci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Details",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "8h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "location" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Location" ], "type": "alias" }
      ],
      [
       { "params": [ "product_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Product" ], "type": "alias" }
      ],
      [
       { "params": [ "code_level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Code Level" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "IO Stats - vDisks - Read",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_id ($tag_node)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_vdisk",
     "select": [
      [
       { "params": [ "rb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 512" ], "type": "math" },
       { "params": [ "rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "IO Stats - vDisks - Write",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_id ($tag_node)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_vdisk",
     "select": [
      [
       { "params": [ "wb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "IO Stats - Ports - Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_id ($tag_node)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "stat_port",
     "select": [
      [
       { "params": [ "hbr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "IO Stats - Ports - Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_id ($tag_node)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "stat_port",
     "select": [
      [
       { "params": [ "hbt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "IO Stats - mDisks - Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_id $col ($tag_node)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_mdisk",
     "select": [
      [
       { "params": [ "rb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 512" ], "type": "math" },
       { "params": [ "rx" ], "type": "alias" }
      ],
      [
       { "params": [ "wb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 512" ], "type": "math" },
       { "params": [ "tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "IO Stats - mDisks - Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_id $col ($tag_node)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_mdisk",
     "select": [
      [
       { "params": [ "rq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "rq" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  }
 ]
}